#### Preamble ####
# Purpose: Tests the structure and validity of the simulated_data electoral divisions dataset.
# Author: Haowei Fan, Fangning Zhang, Shaotong Li
# Date: 13 October 2024
# Contact: haowei.fan@mail.utoronto.ca
# License: MIT
# Pre-requisites: Requires simulated data files generated by 00-simulate_data.R
# Any other information needed? None

library(tidyverse)

# Function to test individual candidate datasets
test_simulated_candidate_data <- function(data, candidate_name) {
  message(paste("Testing data for", candidate_name))
  
  # Test if the data was successfully loaded
  if (exists("data")) {
    message("Test Passed: The dataset was successfully loaded.")
  } else {
    stop("Test Failed: The dataset could not be loaded.")
  }
  
  # Check if the dataset has 500 rows
  if (nrow(data) == 500) {
    message("Test Passed: The dataset has 500 rows.")
  } else {
    stop("Test Failed: The dataset does not have 500 rows.")
  }
  
  # Check if the dataset has 10 columns
  if (ncol(data) == 10) {
    message("Test Passed: The dataset has 10 columns.")
  } else {
    stop("Test Failed: The dataset does not have 10 columns.")
  }
  
  # Check value ranges and types for specific columns
  if (all(data$numeric_grade >= 0 & data$numeric_grade <= 10)) {
    message("Test Passed: All 'numeric_grade' values are within the range 0-10.")
  } else {
    stop("Test Failed: 'numeric_grade' contains values outside the range 0-10.")
  }
  
  if (all(data$pollscore >= 0 & data$pollscore <= 10)) {
    message("Test Passed: All 'pollscore' values are within the range 0-10.")
  } else {
    stop("Test Failed: 'pollscore' contains values outside the range 0-10.")
  }
  
  if (all(data$transparency_score >= 0 & data$transparency_score <= 10)) {
    message("Test Passed: All 'transparency_score' values are within the range 0-10.")
  } else {
    stop("Test Failed: 'transparency_score' contains values outside the range 0-10.")
  }
  
  # Check categorical values for methodology and population
  if (all(data$methodology %in% c("level1", "level2", "level3", "level4"))) {
    message("Test Passed: 'methodology' column contains only valid levels.")
  } else {
    stop("Test Failed: 'methodology' column contains invalid levels.")
  }
  
  if (all(data$population %in% c("a", "v", "lv", "rv"))) {
    message("Test Passed: 'population' column contains only valid categories.")
  } else {
    stop("Test Failed: 'population' column contains invalid categories.")
  }
  
  # Check if 'hypothetical' is only TRUE or FALSE
  if (all(data$hypothetical %in% c(TRUE, FALSE))) {
    message("Test Passed: 'hypothetical' column contains only TRUE or FALSE values.")
  } else {
    stop("Test Failed: 'hypothetical' column contains invalid values.")
  }
  
  # Check for missing values
  if (all(!is.na(data))) {
    message("Test Passed: The dataset contains no missing values.")
  } else {
    stop("Test Failed: The dataset contains missing values.")
  }
  
  # Check for unique 'poll_id'
  if (n_distinct(data$poll_id) == nrow(data)) {
    message("Test Passed: 'poll_id' column contains unique values.")
  } else {
    stop("Test Failed: 'poll_id' column contains duplicate values.")
  }
}

# Load and test each candidate's data
candidate_files <- list("candidate_1" = "data/00-simulated_data/simulated_candidate_1.csv",
                        "candidate_2" = "data/00-simulated_data/simulated_candidate_2.csv",
                        "candidate_3" = "data/00-simulated_data/simulated_candidate_3.csv")

for (candidate_name in names(candidate_files)) {
  data <- read_csv(candidate_files[[candidate_name]])
  test_simulated_candidate_data(data, candidate_name)
}
